export const FIELD_LABELS: Record<string, string> = {
  supplier: "Lieferant",
  invoiceNumber: "Rechnungsnummer",
  invoiceDate: "Rechnungsdatum",
  deliveryDate: "Lieferdatum",
  servicePeriodStart: "Leistungsbeginn",
  servicePeriodEnd: "Leistungsende",
  totalAmountCents: "Bruttobetrag",
  netAmountCents: "Nettobetrag",
  vatAmountCents: "Umsatzsteuerbetrag",
  vatRate: "Umsatzsteuersatz",
  quantityLiters: "Heizölmenge",
  consumptionKwh: "Stromverbrauch",
  meterNumber: "Zählernummer",
  priceMicroEuroPerKwh: "Arbeitspreis",
  monthlyBasePriceCents: "Monatlicher Grundpreis",
  tariffValidFrom: "Tarif gültig ab",
  tariffValidTo: "Tarif gültig bis",
  co2CostCents: "CO₂-Kosten",
  co2Grams: "CO₂-Ausstoß",
  energyContentKwh: "Energiegehalt",
  emissionFactorMicrogWh: "Emissionsfaktor",
  annualAllocatableAmountCents: "Wohnanteil Grundsteuer",
  annualRateMicroCentsPerM2: "Grundsteuersatz je m²",
};
export const SECTION_LABELS: Record<string, string> = {
  HEATING_OIL: "Heizöl",
  WARTUNG: "Wartung und Service",
  SCHORNSTEINFEGER: "Schornsteinfeger",
  EMISSIONSMESSUNG: "Emissionsmessung",
  PRÜFUNG: "Prüfung",
  BETRIEBSSTROM: "Betriebsstrom",
  SCHLAMMABFUHR: "Entleerung und Schlammentsorgung",
  WASSER: "Wasserversorgung",
  GRUNDGEBÜHR: "Grundgebühr",
  GEBÜHREN: "Gebühren",
  BESCHEID: "Steuerbescheid",
  TARIF: "Stromtarif",
  JAHRESRECHNUNG: "Jahresrechnung",
  REPARATUR: "Reparatur (Vermieter)",
  ERSATZ: "Erneuerung (Vermieter)",
  SANIERUNG: "Sanierung (Vermieter)",
  MODERNISIERUNG: "Modernisierung (Vermieter)",
  SONSTIGES: "Sonstige Position",
  OPERATING: "Betriebskosten",
};
export const FORMAT_LABELS: Record<string, string> = {
  TEXT: "Text",
  DATE: "Datum",
  CENTS: "Eurobetrag",
  DECIMAL: "Dezimalzahl",
  PERCENT: "Prozentsatz",
  GRAMS: "CO₂-Menge",
  MICRO_EURO: "Europreis mit sechs Nachkommastellen",
};
